### PR TITLE
chore: add lock file

### PR DESCRIPTION
**Pull request by joscha**
refs https://github.com/dprint/dprint-plugin-typescript/pull/140#issuecomment-881138094

### CODE REVIEW

**Comment by dsherret** [comment]
@joscha thanks for opening this, but I'd prefer not to add a lockfile because it's good to get notified as soon as possible about when a new patch release of a dependency breaks the tests or build because that would affect downstream binaries such as Deno which wouldn't rely on the lockfile in this crate.

Plus, it's not recommended to check in the Cargo.lock file for libraries and only binaries. For example:

```
> cargo new testing --lib
     Created library `testing` package
> cd testing
> cat .gitignore
/target
Cargo.lock
```

More information on the reasoning is here: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by joscha** [comment]
Ok, fair. It just felt strange that when I forked the repo the build failed that was passing on the upstream the week before...

**Comment by dsherret** [comment]
Yeah, I know it’s strange. At least it’s rare for that to occur.

**Comment by dsherret** [comment]
I've decided to go against Rust's recommendation and include lockfiles in lib repos now. It can be useful to analyze when upgrading dependencies in order to see what's new (lockfile incoming soon).

**Pull request closed without merging**
