### PR TITLE
Ensure if body stays on same line when condition is multiline

### LINKED ISSUE #359: If body always moves to new line when condition spans multiple lines
**Describe the bug**

dprint-plugin-typescript version: 0.68.0

I set everything to "maintain", but when this if statement gets reprinted, the return moves to a new line separate from the closing `)` of the if statement condition, as though the "maintain" setting checks to see if the body is on a new line via checking the location of the keyword rather than the text that precedes it.

Config:

```json
{
  "indentWidth": 4,
  "lineWidth": 120,
  "newLineKind": "auto",
  "quoteStyle": "preferDouble",
  "useBraces": "maintain",
  "operatorPosition": "maintain",
  "nextControlFlowPosition": "maintain",
  "bracePosition": "maintain",
  "singleBodyPosition": "maintain"
}
```

**Input Code**

```ts
if (someFunction({ xyz: 1234 })) return;

if (someFunction({
    xyz: 1234
})) return;
```

**Expected Output**

```ts
if (someFunction({ xyz: 1234 })) return;

if (
    someFunction({
        xyz: 1234,
    })
) return;
```

or

```ts
if (someFunction({ xyz: 1234 })) return;

if (someFunction({
    xyz: 1234
})) return;
```

**Actual Output**

```ts
if (someFunction({ xyz: 1234 })) return;

if (
    someFunction({
        xyz: 1234,
    })
)
    return;
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #359.

I'm a noob in this codebase, let me know if I've missed something obvious!

### CODE REVIEW

**Comment by jakebailey** [comment]
I've tested this on the TS codebase, and it does appear to work (I haven't noticed any oddities so far)

**Review by dsherret — APPROVED** [review]
Looks really good to me! Thanks!

> I'm a noob in this codebase, let me know if I've missed something obvious!

This is a really hard codebase 😅. It used to be even more complex because there used to be no way to go up the ancestor nodes.

**Comment by jakebailey** [comment]
More of a discoverability problem than anything... that and realizing what a Condition was doing.

**Comment by dsherret** [comment]
@jakebailey yeah, I need to spend more time documenting stuff. The codebase has had so much churn though (ex. you used to not be able to get tokens from a node). There's a bit of an overview on the IR here: https://github.com/dprint/dprint/blob/main/docs/overview.md (it's missing explaining the recent concept of "anchors" though)

**Comment by jakebailey** [comment]
It turns out my fix wasn't complete; I should have also had a test for `useBraces: whenNotSingleLine`, as that appears to see a multi-line conditional and then add braces. I guess that's probably a different bug (just one that wouldn't have appeared previously).

**Pull request merged**
