### PR TITLE
Fix placement of template literals in arrow bodies

### LINKED ISSUE #117: weird placement of opening backtick from arrow function return
**Describe the bug**

dprint-plugin-typescript version: 0.41.0 (I guess? how would I find out?)

Opening backticks of template literals get placed on new lines when returned from arrow functions but are kept on the same line for assignments and returns from regular functions.

**Input Code**

```ts
const a = `
    test
`

const b = () => `
    test
`

function c () {
    return `
        test
    `
}
```

**Expected Output**

```ts
const a = `
    test
`;

const b = () => `
    test
`;

function c() {
    return `
        test
    `;
}
```

**Actual Output**

```ts
const a = `
    test
`;

const b = () =>
    `
    test
`;

function c() {
    return `
        test
    `;
}
```

https://dprint.dev/playground/#code/MYewdgzgLgBAhjAvDABgWAFA2zKBTaTdDTUSWAIyRgAoBKJAPlUx1wKiM0wDMBXMMCgBLcDGC0GAb1Y4ATnih85YFljY58hddmIBfIA/language/typescript

### PR DESCRIPTION
**Pull request by kdy1**
Closes #117.

If you are not going to squash it, please tell me so I can squash it :)

### CODE REVIEW

**Comment by dsherret** [comment]
Thanks @kdy1! It looks good, but I think there might need to be some heuristic for deciding whether to newline or not. For example, prettier does this:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYAUAlPgHyYAGOMAllAObYAWtamEArljfU742xwMfISKiYGA-sLqNKAHShLIUXBBjM4AJ3xFSeCotizRMcxctXrN23fsPbSx5dPylK9Fg1btAJj0SciVjaWwXCMioyOdItwZjEAAaEAgABzp0ZFAAQ21tCAB3AAU8hDRkEByAG0KcgE8KlIAjbRywAGs4GABlNPa+ZBhtTjgUuABbZrgAExnZgBkcxk4chjgAMQhtCZzzQZQc7ghkkGYYCeqAdVYcfrA4HvLaOgA3F-rKsDQmkHo0HQwYptBi7ZAAMxqAJSACs0AAPABCbU63R6OQmcAW9DgEKhYxAcPhPT41TgAEVOBpcUhIdVoSB+toAdpKs0ctNqqc0tp6DArrQZppkAAOAAMKR5EABVzaaUqPOEOleuJSAEcqfBgekKoc0ABaKBwWazU7aOAa2jm4FrMG0-EpAETWhDEYEtCkimaml0hkwDkCoXMZB+FLDHK0ap8ADCEAmdpAwgArKdOACACoc3W+gmvUYASSg81gPTAvIyAEEiz0YPUyXj6XAAL5NoA

I'm not sure what that heuristic should be though. I'll look at this more later and merge it soon!

**Comment by kdy1** [comment]
@dsherret I modified it a bit, but I didn't implement preserving of the original line when it starts with a newline character.
It's because I'm not sure if it's desirable and I'd like to ask if you want it.

**Comment by dsherret** [comment]
@kdy1 thanks! It looks good. I will take a look at this in more detail and merge it soon.

**Comment by dsherret** [comment]
Apologies for my delay. Thanks for this change, @kdy1!

**Pull request merged**
