### PR TITLE
feat: add config for forced multiline named imports/exports

### PR DESCRIPTION
**Pull request by jakebailey**
For #453.

This just does imports/exports; I'm not totally confident in the implementation or its naming, either. I just thought I'd throw an idea out there.

### CODE REVIEW

**Comment by jakebailey** [comment]
Spent some time thinking about it, and I feel like it shouldn't be a boolean, but two options, one which allows `import { justOneThing } from "foo"` and one which doesn't.

**Comment by dsherret** [comment]
> Spent some time thinking about it, and I feel like it shouldn't be a boolean, but two options, one which allows `import { justOneThing } from "foo"` and one which doesn't.

I think you're right. I think it's ok to land this as a boolean for now though.

**Review by dsherret — APPROVED** [review]
LGTM! I don't see any issues :)

I made the config name shorter.

In the interest of time, let's land this one and then if you'd like you can submit a follow up PR with it not being a boolean. I think maybe something like `"always" | "multiple" | "something for this being off that I can't think of... maybe just 'off' or 'lineWidth'...not sure"`.

**Comment by jakebailey** [comment]
Thanks for reviewing! (These PRs are the only Rust I've actually written, so, shocked I don't have more trouble.)

**Pull request merged**
