### PR TITLE
Support "continuation indent" from IntelliJ

### PR DESCRIPTION
**Pull request by TerrorJacktyl**
# Problem

IntelliJ allows controlling multiples of indentation for specific nodes [**continuation indent**.](https://www.jetbrains.com/help/idea/code-style-sql-tabs-and-indents.html) This is where we allow a different amount of indentation for specific expressions that are split across multiple lines. [See this comment below for some examples of IntelliJ's behaviour.](https://github.com/dprint/dprint-plugin-typescript/pull/486#issuecomment-1437660048)

Existing behaviour:

```
~~ lineWidth: 20, indentWidth: 4, preferHanging: true ~~
== should indent a hanging parameter list twice ==
foo(one, two, three, four, five);

[expect]
foo(one, two, three,
    four, five);             <-- note 4 spaces of indent here
```

We would like to be able to support the following:

```
~~ lineWidth: 20, indentWidth: 4, hangingIndentTimes: 2, preferHanging: true ~~
== should indent a hanging parameter list twice ==
foo(one, two, three, four, five);

[expect]
foo(one, two, three,
        four, five);         <-- note 8 spaces of indent here
```

# Solution

Add several options for controlling the wrapping indent. Additionally, add options for controlling the multiline indent for several multiline structures (like arrays, arguments and objects).

Note that this also depends on [a change to the core `dprint` which **is not backwards-compatible**](https://github.com/dprint/dprint/pull/629) for dependent plugins.

```
"hanging.IndentTimes": {
  "description": "How many indentations should be applied after a hanging line break. Also commonly referred to as \"continuation indent\".",
  "type": "number",
  "default": 1
},
"multiLine.IndentTimes": {
  "description": "How many indentations should be applied after a line break that begins multiline.",
  "type": "number",
  "default": 1
},
"objectLike.indentTimes": {
  "description": "How many indentations should be applied after a line break that begins multiline for objects and object-destructures.",
  "type": "number",
  "default": 1
},
"arrayLike.indentTimes": {
  "description": "How many indentations should be applied after a line break that begins multiline for arrays and array-destructures.",
  "type": "number",
  "default": 1
}
```

### CODE REVIEW

**Comment by dsherret** [comment]
I'm not sure about this one because it's another thing to worry about all the time. Why doesn't a single indentation suffice for readability? Are there some other examples?

**Comment by adrian-gierakowski** [comment]
@JayZ2398 I have never seen such setting in a code formatter and the links you've provided also don't seem to contain any example of such option.

**Comment by JayZ2398** [comment]
> are there some other examples?

I'll elaborate on [an example in IntelliJ's documentation.](https://www.jetbrains.com/help/idea/settings-code-style-javascript.html#tabs_and_indents) Their `Continuation indent` config option is available for every language. It controls "the number of spaces to be inserted between the elements of **an array**, in **expressions**, **method declarations**, and **method calls**." Here's a visual example from IntelliJ's settings for Typescript (but you can do this for almost any language supported by IntelliJ).

If `ContinuationIndent != Indent`:
image

If `ContinuationIndent == Indent`:
image

**Comment by JayZ2398** [comment]
> I'm not sure about this one because it's another thing to worry about all the time.

Why would this change be something to worry about all the time? In the core, I've modified the `MultiLineOptions` [helpers to take some `*_indent_times` arguments](https://github.com/dprint/dprint/pull/629/files#diff-1b5f5a0428033aa5ae0d4f2cbb13980abe7edd73d58bbc6efe0af720e186ea87R41). If we don't want all dprint plugins to have to specify the amount of indent times (and care about them all the time), I could make these arguments optional.

> Why doesn't a single indentation suffice for readability?

At Canva we came to dprint hoping to combine the things we liked about Prettier with the things we liked about IntelliJ formatting. We think continuation indent is pretty neat so we'd like to add it to dprint too. Naturally we're biased by our own preferences, but I thought this change would [align with dprint's ideals:](https://dprint.dev/)

> 3. Official plugins are highly configurable

I'm curious to hear more of your thoughts. Thanks for your time so far!

**Comment by JayZ2398** [comment]
> @adrian-gierakowski  the links you've provided also don't seem to contain any example of such option.

Yeah those docs aren't the best, for VSCode a better example is found by looking at the settings directly:
image

In this case, `deepIndent` in VSCode is like having `ContinuationIndent = 2 * Indent* in IntelliJ.

I hope that helps!

**Comment by declanvong** [comment]
>I have never seen such setting in a code formatter and the links you've provided also don't seem to contain any example of such option.

Some more information is available in this ticket: https://github.com/dprint/dprint-plugin-typescript/issues/286

**Pull request closed without merging**
